### ISSUE TITLE
feature request: twig pagination

### ISSUE THREAD

**Issue by gigago** [getgrav/grav-plugin-pagination#13]
I do this with the following code in pagination.php. Hand-kludged from the existing code base, please improve whenever deemed necessary :-) At present, I call this from a twig simplefunc extension, worgs great! Maybe someone has a better proposal for integrating this functionality into grav.

```
use Grav\Common\Uri;

  /**
     * 'runtime' pagination
     *
     * @param collection $collection
     * @param $limit
     */
    public function paginateCollection(Collection $collection, $limit)
    {
        $collection->setParams(['pagination' => 'true']);
        $collection->setParams(['limit' => $limit]);

        if ($collection->count() > $limit) {
            require_once __DIR__ . '/classes/paginationhelper.php';
            $this->pagination = new PaginationHelper($collection);
            $collection->setParams(['pagination' => $this->pagination]);

            $uri = $this->grav['uri'];
            $start = ($uri->currentPage() - 1) * $limit;

            if ($limit && $collection->count() > $limit) {
                $collection->slice($start, $limit);
            }
        }
    }
```

**Comment by flaviocopes** [comment]
Can you explain what this does and how should this be used / how do you use it?

**Comment by gigago** [comment]
Sure, you're welcome. I created a wrapper function in twigextension:

public function paginateFunc($collection,$limit) {
        $pag = new \Grav\Plugin\PaginationPlugin($this, $this->grav, $this->config);
        return $pag->paginateCollection($collection,$limit);
    }

So I call this function from twig, feeding it *any* available page collection and a limit. Specifically, I create different views of a collection of pages (events in this case), the size of which depends on taxonomy or other parameters. The twig temple should also contain the call to pagination.html.twig, as per usual.

Please note, that at present any existing pagination parameters are simply overwritten. It should be possible to check for that. Also, I think disabling pagination may be necessary when using this function on a header collection.

More questions? Don't hesitate to ask.

**Comment by gigago** [comment]
Final version changes the following things:

* ignore_url_params passed through pagination functions, default false
* no more global ignore_url_params setting
* twig extension in plugin folder

Default behaviour of pagination plugin unchanged, only the twig extension uses the parameters

/*pagination.php*/

/**
 * twig pagination
 *
 * @param collection $collection
 * @param $limit
 */
public function paginateCollection( $collection, $limit, $ignore_url_params = true )
{
    $collection->setParams(['pagination' => 'true']);
    $collection->setParams(['limit' => $limit]);
    $collection->setParams(['ignore_url_params' => $ignore_url_params]);

    if ($collection->count() > $limit) {
        require_once __DIR__ . '/classes/paginationhelper.php';
        $this->pagination = new PaginationHelper($collection);
        $collection->setParams(['pagination' => $this->pagination]);

        $uri = $this->grav['uri'];
        $start = ($uri->currentPage() - 1) * $limit;

        if ($limit && $collection->count() > $limit) {
            $collection->slice($start, $limit);
        }
    }
}

--------------------------------------------------------------------------------------------------------------------------------------------

/* paginationhelper.php */

$url_params = ($collection->params()['ignore_url_params'])?
    ([]):(explode('/', ltrim($uri->params(), '/')));

--------------------------------------------------------------------------------------------------------------------------------------------

/* pagination/twig/PaginationTwigExtension.php */

<?php
namespace Grav\Plugin;

use \Grav\Common\Grav;

class PaginationTwigExtension extends \Twig_Extension
{

    protected $config;

    public function __construct()
    {
        $this->config = Grav::instance()['config'];
    }

    /**
     * Returns extension name.
     *
     * @return string
     */
    public function getName()
    {
        return 'PaginationTwigExtension';
    }

    /**
     * Return a list of all functions.
     *
     * @return array
     */
    public function getFunctions()
    {
        return [
            new \Twig_SimpleFunction('paginate', [$this, 'paginateFunc']),
        ];
    }

    public function paginateFunc($collection, $limit, $ignore_url_params) {
        $pag = new PaginationPlugin($this, Grav::instance(), $this->config);
        $pag->paginateCollection($collection, $limit, $ignore_url_params);
    }
}

**Comment by Sogl** [comment]
@gigago Good change. Why not making a PR?

**Comment by gigago** [comment]
Just made a pull request for this code.

**Comment by Sogl** [comment]
@gigago Can you give me a link? Can't see any PR in this repo.

**Comment by gigago** [comment]
https://github.com/gigago/grav-plugin-pagination/pull/1

Sorry I’m a beginner in git. Pretty sure I made some mistakes.

**Comment by Sogl** [comment]
You made a PR in your own plugin fork, but need to do this here ;)

**Comment by gigago** [comment]
I suspected something like that. No problem, was a nice excercise, PR coming =)

**Comment by inktrap** [comment]
@gigago This is such a nice addition … would be a shame to forget the PR ;)
👍

**Comment by rhukster** [comment]
Was there ever a pull request created for this?

**Comment by gigago** [comment]
This has been merged last year: https://github.com/getgrav/grav-plugin-pagination/pull/22

**Comment by inktrap** [comment]
So, this can be closed?!
