### ISSUE TITLE
pagination object not global in template

### ISSUE THREAD

**Issue by fvsch** [getgrav/grav-plugin-pagination#17]
I’m using Grav v1.0.10 and installed the pagination plugin with `bin/gpm install pagination`.

I’m making pages and templates from scratch. My page has subpages and this YAML front matter:

```yaml
title: News
content:
    items:
        '@self.children'
    order:
        by: date
        dir: desc
    limit: 5
    pagination: true
pagination: true
```

(I tried adding the `pagination` key at two different levels, because I found it at those 2 places depending on the documentation or examples I could find.)

In the template, the `pagination` object does not exist. After `dump()`ing things for ages in the debug console, I was able to find that `page.collection.params.pagination` gives me access to this object.

So when I use:
```twig
{% include 'partials/pagination.html.twig' %}
```
(using the plugin’s template), it doesn’t work because the default template tries to use the global `pagination` object. But this works alright:

```twig
{% include 'partials/pagination.html.twig' with {
    pagination: page.collection.params.pagination
} %}
```

Also adding `/page:2` to the URL works well (it filters the `page.collection()`). So it’s not a problem of the plugin not working. Just `pagination` not being global (as the template expects).

Is that expected behavior? If it is expected behavior, could this be documented in the README for this project?

As a side note, it might be useful to add some information about including the `partials/pagination.html.twig` template if users want to actually have pagination visible in the page. And fixing the broken link in the README (goes to `templates/pagination.html.twig`, missing the `partials/` part).

**Comment by flaviocopes** [comment]
There's no global `pagination` object, it must be passed to the twig.

Most (all?) themes currently use

```twig
{% set collection = page.collection() %}

{% include 'partials/pagination.html.twig' with {'base_url':page.url, 'pagination':collection.params.pagination} %}
```

`partials/pagination.html.twig` could as well set `page.collection.params.pagination` as the default if not set.

I've just added a commit to address this: https://github.com/getgrav/grav-plugin-pagination/commit/1d64c6e5f00e2666f8f326d0dc25366b2ad5e0bd

And fixed the `partial/` in the readme

**Comment by fvsch** [comment]
Thanks, this is fixed for me on the code side. I added a PR for clarifying the documentation on this and a few other things.
