### ISSUE TITLE
Can't get Pagination to do page count for current language only

### ISSUE THREAD

**Issue by fredericmohr** [getgrav/grav-plugin-pagination#20]
Hi, i have a problem with the pagination plugin I can't get fixed. I changed my blog page twig template to only display posts from the current language, but the pagination still counts all available posts (en fallback) which results in /blog/page:1 showing 1 post, /blog/page:2 showing 0 and /blog/page:3 showing 1 in german, while the english website shows 4 on page:1, 5 on page:2 and 4 on page:3. 

I couldn't find a way to tell the pagination to ignore pages that are not available in the current lang (or to set it in the blog pages "blog list -> max item count" setting).

Is this not yet supported by pagination? Or is there something I've missed?

**Comment by flaviocopes** [comment]
Pages fallback to english. To remove a page from a language, you create that page in the language and then you set it as unpublished https://learn.getgrav.org/content/headers#published. That should work.

**Comment by fredericmohr** [comment]
Works flawlessly, thank you so much. This solution is so easy that I'm feeling ashamed trying to fix it so long...

Also, now only post categories that contain posts of the current languages show up.

Loving Grav :)
