### ISSUE TITLE
use of pagination plugin leaves url:page:whatever opened

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav-plugin-pagination#25]
Let's say there are 3 pages on a blog page.
url/page:1
url/page:2
url/page:3
If I ask the url/page:4 or url/page:_whatever_, I should get a 404 error, but I get a blank page.

In my case, therefore I have page referenced by search engines that do not have any content.
Can someone replicate that or is it linked to other parameter like multisite structure of my site?

Thanks in advance for help.

**Comment by ulab** [comment]
I can replicate that using a higher page number than exists, but also with page:0.
