### ISSUE TITLE
Forbidden: You don't have permission to access /page:2 on this server.

### ISSUE THREAD

**Issue by CutmastaD** [getgrav/grav-plugin-pagination#27]
Tried in Wampserver on Windows 10.
I also downloaded the blog-site skeleton to check whether I screwed something up but the problem still occurs. 
I'm pretty sure that I just have to adjust the permissions on a file, but I have no idea which file.
I already tried to `chown -R 776` on `/user/pages` and `/user/plugins/pagination` but that didn't work.

**Comment by rhukster** [comment]
https://learn.getgrav.org/troubleshooting/forbidden

It's the param separator on windows and wampserver.
