### ISSUE TITLE
no base_url

### ISSUE THREAD

**Issue by svartsvan** [getgrav/grav-plugin-pagination#32]
Hello,

clicking on any pagination link, returns https://page:2/

I tried to call {{ base_url }} in user/plugins/pagination/templates/partials/pagination.html.twig

but it's empty. I expect it to be https://{{ domain}}/page:2/

thanks in advance

**Comment by svartsvan** [comment]
already solved it, changed base_url to uri.host

**Comment by rhukster** [comment]
Should be fixed.
