### ISSUE TITLE
Deprecated GravTrait used

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-pagination#33]
The following warning is flooding the Grav debugger:
> Deprecated GravTrait used in [...]/user/plugins/pagination/classes/paginationhelper.php

**Comment by rhukster** [comment]
oh this was cleaned up a while ago, we just never released it! https://github.com/getgrav/grav-plugin-pagination/commit/b1fd0ddee0db67b363cf6095928e8a91a115bec5

Will do so... thanks.
