### ISSUE TITLE
In version 1.4.0 operation of page change omits base_url

### ISSUE THREAD

**Issue by XizzoR** [getgrav/grav-plugin-pagination#34]
Hello!

In Grav 1.5.1 and this plugin with version 1.4.0, changing pages causes anomaly where application calls url `https://page:number` (number represents a page number on which user wants to go). I haven't experienced this problem on earlier versions of Grav and this plugin.

Screenshot (from inspect element in Chrome): https://postimg.cc/image/924avv7bv/

**Comment by rhukster** [comment]
is this SSL specific?

**Comment by rhukster** [comment]
Found it, fixed and released.
