### ISSUE TITLE
Finding Page URL

### ISSUE THREAD

**Issue by ryanwake01** [getgrav/grav-plugin-pagination#5]
I am using a if statement to target the first story in the loop, naming it 'feature-story'. When I use this pagination plugin, that loop starts over, creating a "feature story' on the second page. Is there a way for me to write a if statement that basically creates the feature story ONLY on the first page? Something like:

{% if loop.first and pagination == page1 %}

**Comment by rhukster** [comment]
Have you looked at the `loop.index` and other options that Twig makes available? http://twig.sensiolabs.org/doc/tags/for.html
