### ISSUE TITLE
Change ":" to "-" or "/" in pagination url

### ISSUE THREAD

**Issue by shibinvl** [getgrav/grav-plugin-pagination#55]
**Can you make an update to remove ":" from pagination, url to "-" or "/". for example "domain.com/blog/page:2" to "domain.com/blog/page-2" or "domain.com/blog/page/2" or "domain.com/blog/page2"
#53 
![Screenshot (8)](https://user-images.githubusercontent.com/35234604/125956717-4fc0ecc3-b1c9-4ffa-86a8-b64603b951a4.png)

**Comment by rhukster** [comment]
the `x:y` syntax is Grav's built-in `parameter` standard method of passing information in the URL, it' less ugly than query string.  It's used throughout Grav and is not going to be changed.
