### ISSUE TITLE
Since update to v1.4.5 today, pagination broken, shows https://page:2/

### ISSUE THREAD

**Issue by Moonbase59** [getgrav/grav-plugin-pagination#61]
I updated the pagination plugin today, to version 1.4.5. To be sure, I also cleared the Grav site’s cache using Admin UI, and reindexed TNT search. I used the Admin UI to update.

I’m running [Grav](https://getgrav.org/) v1.7.44 - Admin v1.10.44.

Now, when clicking the page 2 link on my blog, it tries to access `https://page:2/`instead of my site.

Help! What can I do to fix this, or maybe revert to the version before?

**Comment by Moonbase59** [comment]
As an immediate rescue measure, I manually reverted the chenges made in https://github.com/getgrav/grav-plugin-pagination/commit/ed158b015e3d320964af8d08050d59c6e689622d#diff-58a71fdc6dbd0b2aa7dc1c24f1224f6c0fe1d21304e2e87b3914d8b19d952d59 in my file `/user/plugins/pagination/templates/partials/pagination.html.twig`. This at least made the site working again (`https://my.domain.tld/page:2` instead of `https://page:2/`).

**Comment by rhukster** [comment]
Will look into this asap. thanks.

**Comment by rhukster** [comment]
1.4.6 is available with the previous fixes reverted.  I will need to investigate this further as I did test locally and worked fine for me with absolute_url's enabled and disabled.  So something weird going on. I just think the prior fix was working 100% with absolute_url's off. As this is default behavior, and used my 99.9% of people, it's probably best to stick with this version until I can find a proper fix that works for all scenarios.

**Comment by Moonbase59** [comment]
Thanks for the real fast fix! I can confirm v1.4.6 works here again.

Fortunately, the change wasn’t big, so I could fix it by reverting, but yes, it’d be nice to have a solution that works with all setups.
